# Generated by Django 2.2.28 on 2023-05-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiwari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mithi', models.BigIntegerField(blank=True)),
                ('one', models.BigIntegerField(blank=True, null=True)),
                ('two', models.BinaryField(blank=True, null=True)),
                ('four', models.BooleanField(blank=True, null=True)),
                ('five', models.CharField(blank=True, max_length=2562554564653879654687654367896546789645324678964531246574531246587645321456875468746587458765487465864587645879645876458764587645876458764584, null=True)),
                ('three', models.DateField(auto_now_add=True, null=True)),
                ('fivee', models.DurationField(blank=True, null=True)),
                ('high', models.EmailField(blank=True, max_length=254, null=True)),
                ('xvd', models.URLField(blank=True, null=True)),
                ('data', models.UUIDField(blank=True, null=True)),
                ('fdsfsd', models.TimeField(auto_now=True, null=True)),
                ('mith', models.TextField(blank=True, null=True)),
                ('ning', models.SmallIntegerField(blank=True, null=True)),
                ('qwre', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('poi', models.SlugField(blank=True, null=True)),
                ('mjii', models.PositiveIntegerField(blank=True, null=True)),
                ('vvvvvvvfc', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('fcfc', models.IntegerField(blank=True, null=True)),
                ('cfvgvg', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
